### PR TITLE
Allow top-aligned snackbars

### PR DESCRIPTION
**Pull request by kaiwoods**
Adds an option that allows Snackbars to appear at the top of the viewport, rather than the bottom.
Default to the bottom so it doesn't affect the default behaviour.
Also duplicated the animation and made a small amend so that closed messages will fade out up when positioned at the top.

Useful for situations where, for example, we have small message popups, like "10 people recently viewed this product," etc. :)

### CODE REVIEW

**Comment by kaiwoods** [comment]
Please, feel free to close this if there's no interest in it :) this just boils down to CSS changes at the end of the day, so it's not absolutely necessary it becomes part of the library!

**Comment by egoist** [comment]
OK, sorry for the late reply, closing cause Snackbar is designed to be shown at the bottom of viewport.

**Comment by egoist** [comment]
I've seen some use case like this, mayb it's worth adding this 🤔

Screenshot_20190604-132316

**Comment by kaiwoods** [comment]
I do see it often on online stores, also, usually flashing messages stating how many people are viewing/have viewed a product, or similar behaviour.

Snackbar seems more tailored to prompting user actions, but I'm sure it'd be great for quick flash messaging (like in your screenshot), also!

**Comment by PiotrNap** [comment]
Hi, is this feature already available? I saw your PR from a past, but this seems not to working yet. 

> I do see it often on online stores, also, usually flashing messages stating how many people are viewing/have viewed a product, or similar behaviour.
> 
> Snackbar seems more tailored to prompting user actions, but I'm sure it'd be great for quick flash messaging (like in your screenshot), also!

**Comment by kaiwoods** [comment]
@PiotrNap This was never merged - I think it was an undesired feature. I'm not sure how much the codebase has changed since I created the PR, perhaps it's something @egoist can consider revisiting? I'm happy to make any adjustments to my original PR, if needed :)

**Comment by PiotrNap** [comment]
Understood, thanks for your quick reply anyway!

**Pull request closed without merging**
